[versions]
agp = "8.8.0"
gradle = "8.2.0"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
